export const TRANSACTION_DATA_REQUEST="TRANSACTION_DATA_REQUEST"
export const TRANSACTION_DATA_SUCCESS="TRANSACTION_DATA_SUCCESS"
export const TRANSACTION_DATA_FAILURE="TRANSACTION_DATA_FAILURE"


export const DATA_SORT_REQUEST="DATA_SORT_REQUEST"
export const DATA_SORT_SUCCESS="DATA_SORT_SUCCESS"
export const DATA_SORT_FAILURE="DATA_SORT_FAILURE"